<template>
  <!-- Full-screen modal -->
  <div class="fixed inset-0 z-50 flex flex-col" style="background: rgba(0,0,0,0.88)">

    <!-- Top bar — never printed -->
    <div
      class="no-print flex items-center justify-between px-6 py-4 shrink-0 border-b border-white/10"
      style="background: #161616"
    >
      <div>
        <div class="text-white font-semibold text-sm">Report Preview</div>
        <div class="text-white/40 text-xs mt-0.5">
          This is how your PDF will look
        </div>
      </div>
      <div class="flex items-center gap-3">
        <button
          @click="handleCancel"
          class="px-4 py-2 text-xs text-white/60 hover:text-white border border-white/15
                 hover:border-white/30 rounded-lg transition-colors"
        >
          Cancel
        </button>
        <button
          @click="handlePrint"
          class="px-4 py-2 text-xs font-semibold text-white rounded-lg transition-colors
                 flex items-center gap-2"
          style="background: #c0392b"
        >
          <!-- Download icon -->
          <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24"
               fill="none" stroke="currentColor" stroke-width="2.5">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="7 10 12 15 17 10"/>
            <line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
          Confirm & Download
        </button>
      </div>
    </div>

    <!-- Preview scroll area -->
    <div class="no-print flex-1 overflow-auto flex flex-col items-center py-10 px-4 gap-2">
      <p class="text-white/30 text-xs mb-2">A4 format · Scroll to see full report</p>

      <!-- Scaled A4 preview -->
      <div
        :style="{
          width: '794px',
          transform: `scale(${scale})`,
          transformOrigin: 'top center',
          marginBottom: `${bottomCompensation}px`,
        }"
      >
        <div id="chat-report-print-content" ref="printRef"
             style="background: white; width: 794px; padding: 48px 56px;
                    box-sizing: border-box; min-height: 1123px; font-family: Georgia, serif;">

          <!-- Report header -->
          <div style="display:flex; justify-content:space-between; align-items:flex-start;
                      padding-bottom: 16px; border-bottom: 2px solid #c0392b; margin-bottom: 28px;">
            <div>
              <div style="font-size: 20px; font-weight: 800; color: #c0392b; letter-spacing: -0.5px;">
                RedSage
              </div>
              <div style="font-size: 13px; color: #444; margin-top: 2px;">
                AI-Generated Project Report
              </div>
            </div>
            <div style="text-align: right; font-size: 11px; color: #888; line-height: 1.6;">
              <div>{{ generatedOn }}</div>
              <div>Confidential</div>
            </div>
          </div>

          <!-- Report body: rendered markdown -->
          <div
            class="report-body"
            v-html="renderedContent"
            style="font-size: 13px; line-height: 1.75; color: #1a1a1a;"
          />

          <!-- Footer -->
          <div style="margin-top: 48px; padding-top: 12px; border-top: 1px solid #e5e7eb;
                      display: flex; justify-content: space-between;
                      font-size: 10px; color: #aaa;">
            <span>Generated by RedSage · Confidential</span>
            <span>{{ generatedOn }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import MarkdownIt from 'markdown-it'
import DOMPurify from 'dompurify'

const props = defineProps<{ content: string }>()
const emit = defineEmits<{ (e: 'close'): void }>()

const printRef = ref<HTMLElement | null>(null)
const scale = ref(0.72)
const bottomCompensation = ref(0)
const printClone = ref<HTMLElement | null>(null)

const md = new MarkdownIt({ html: false, linkify: true, breaks: true })

const renderedContent = computed(() =>
  DOMPurify.sanitize(md.render(props.content || ''))
)

const generatedOn = new Date().toLocaleString()

function updateScale() {
  const available = window.innerWidth - 80
  scale.value = Math.min(0.75, available / 794)
  if (printRef.value) {
    bottomCompensation.value = printRef.value.scrollHeight * (scale.value - 1)
  }
}

function cleanupPrintClone() {
  if (printClone.value?.parentElement) {
    printClone.value.parentElement.removeChild(printClone.value)
  }
  printClone.value = null
}

function preparePrintClone() {
  cleanupPrintClone()
  if (!printRef.value) return

  const clone = printRef.value.cloneNode(true) as HTMLElement
  clone.id = 'chat-report-print-content'
  clone.style.transform = 'none'
  clone.style.marginBottom = '0'
  document.body.appendChild(clone)
  printClone.value = clone
}

function handlePrint() {
  preparePrintClone()
  document.body.classList.add('print-report-mode')
  window.addEventListener('afterprint', onAfterPrint, { once: true })
  window.print()
}

function onAfterPrint() {
  document.body.classList.remove('print-report-mode')
  cleanupPrintClone()
  emit('close')
}

function handleCancel() {
  emit('close')
}

onMounted(() => {
  updateScale()
  window.addEventListener('resize', updateScale)
  setTimeout(updateScale, 150)
})

onBeforeUnmount(() => {
  document.body.classList.remove('print-report-mode')
  cleanupPrintClone()
  window.removeEventListener('resize', updateScale)
})
</script>

<style scoped>
/* Markdown content styles for the white preview */
.report-body :deep(h1) {
  font-size: 20px; font-weight: 700; color: #111;
  margin: 24px 0 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px;
}
.report-body :deep(h2) {
  font-size: 16px; font-weight: 700; color: #222; margin: 20px 0 6px;
}
.report-body :deep(h3) {
  font-size: 14px; font-weight: 600; color: #333; margin: 16px 0 4px;
}
.report-body :deep(p) { margin: 8px 0; color: #1a1a1a; }
.report-body :deep(ul), .report-body :deep(ol) {
  margin: 8px 0 8px 20px; color: #1a1a1a;
}
.report-body :deep(li) { margin: 3px 0; }
.report-body :deep(strong) { color: #111; font-weight: 700; }
.report-body :deep(table) {
  width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 12px;
}
.report-body :deep(th) {
  background: #f3f4f6; padding: 8px 12px; text-align: left;
  font-weight: 700; border: 1px solid #e5e7eb; color: #111;
  text-transform: uppercase; font-size: 10px; letter-spacing: 0.05em;
}
.report-body :deep(td) {
  padding: 7px 12px; border: 1px solid #e5e7eb; color: #222;
}
.report-body :deep(tr:nth-child(even) td) { background: #f9fafb; }
.report-body :deep(blockquote) {
  border-left: 3px solid #c0392b; padding: 8px 16px;
  margin: 12px 0; background: #fef9f9; color: #555; font-style: italic;
}
.report-body :deep(code) {
  background: #f3f4f6; padding: 1px 5px; border-radius: 3px;
  font-size: 11px; color: #c0392b;
}
.report-body :deep(pre) {
  background: #f3f4f6; padding: 12px; border-radius: 6px;
  font-size: 11px; overflow-x: auto; margin: 12px 0;
}
.report-body :deep(hr) {
  border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;
}
</style>